### ISSUE TITLE
Can we change the folder called tests to steps?

### ISSUE THREAD

**Issue by philipbeadle** [getgauge-contrib/gauge-js#41]
Hi,
Can you please change the folder thats got the steps in it to step from tests?  Its a bit confusing.

Cheers
Phil

**Comment by kaustavdm** [comment]
@renjithgr and I had this discussion early this year, and ended up renaming the step implementations directory from `src/` to `tests/` in ae0ee37d667. The rationale for that change was to comply with the usual convention in the JavaScript world. Tools like mocha, jasmine etc, expect your test implemetations to be in a `tests` directory by default. Hence, that name.

FWIW, [gauge-java](https://github.com/getgauge/gauge-java) puts its implementations under `src/` as per Java conventions.

However, it should not be difficult to expose a configuration option in `js.properties` to specify custom implementation directory. But, I'm not sure if we should do that because I am not sure if any other gauge language runners do it.

**Comment by kaustavdm** [comment]
Closing this now. If we decide to customize the implementation anytime in the future, we can log it separately and refer this issue.
