### ISSUE TITLE
Timeout error is masking the actual error in async tests

### ISSUE THREAD

**Issue by sguptatw** [getgauge-contrib/gauge-js#78]
**Expected behavior**
Should show the real reason of failure

**Actual behavior**
Getting the timeout error

**Steps to replicate**
* Run lsp tests on windows
> Observe error when screenshot cannot be taken

```
P PError: spawnSync gauge_screenshot ENOENT
 F
        Failed Step: autocomplete at line "4" character "7" should give steps
        Specification: specs\autocomplete.spec:18
        Error Message: Error: Timed out
        Stacktrace:
        Error: Timed out
            at Timeout.<anonymous> (<path>\AppData\Roaming\gauge\plugins\js\2.0.3.nightly-2017-11-23\src\test.js:42:23)
            at ontimeout (timers.js:469:11)
            at tryOnTimeout (timers.js:304:5)
            at Timer.listOnTimeout (timers.js:264:5)
```
**Version**
```
Gauge version: 0.9.5.nightly-2017-11-23
Commit Hash: 51cfe8d

Plugins
-------java (0.6.6.nightly-2017-10-26)
js (2.0.3.nightly-2017-11-23)
screenshot (0.0.1)
```

**Comment by kashishm** [comment]
The js runner is just printing the screenshot error on the console which is related to #77 and it doesn't have any impact on the execution or step failure.

Regarding the timeout error, this is happening because the step execution did not complete in `20` seconds. It works fine, after increasing it to `60` seconds in `js.properties` file. So, It is working as expected and the timeout error which is shown in the console is the original error.
